package me.alexy.hipipl.feature.auth

import java.security.MessageDigest
import java.security.SecureRandom
import kotlin.io.encoding.Base64
import kotlin.io.encoding.ExperimentalEncodingApi

/**
 * Standard RFC 7636 PKCE (S256) code_verifier/code_challenge pair, generated by the app itself
 * rather than the VK ID SDK. Passing the resulting challenge into [com.vk.id.auth.VKIDAuthUiParams]
 * makes the SDK skip its own code->token exchange (its `onAuth` callback won't fire) and hand back
 * the raw auth code via `onAuthCode` instead, which we then exchange ourselves against
 * `POST /api/v1/login_vk` together with the [code_verifier][generateVerifier] we kept.
 */
internal object PkceGenerator {
    private const val VERIFIER_LENGTH = 64
    private val allowedChars = (('A'..'Z') + ('a'..'z') + ('0'..'9') + listOf('-', '.', '_', '~'))

    fun generateVerifier(): String {
        val random = SecureRandom()
        return (1..VERIFIER_LENGTH).map { allowedChars[random.nextInt(allowedChars.size)] }.joinToString("")
    }

    @OptIn(ExperimentalEncodingApi::class)
    fun deriveChallenge(verifier: String): String {
        val digest = MessageDigest.getInstance("SHA-256").digest(verifier.toByteArray(Charsets.US_ASCII))
        return Base64.UrlSafe.encode(digest).trimEnd('=')
    }
}
